# Generated by Django 5.2.1 on 2025-07-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskattachmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentS3MetaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_file_key', models.CharField(max_length=200)),
                ('attachment_id', models.IntegerField()),
            ],
        ),
    ]
