# Generated by Django 5.2.1 on 2025-07-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_attachments3metamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachmentmodel',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.taskmodel'),
        ),
    ]
